### ISSUE TITLE
Upload Boost not Boosting

### ISSUE THREAD

**Issue by Slybianco** [kotatogram/kotatogram.github.io#1]
Howdy, I'm experiencing an issue with the upload boost. It should work on every file, but is working only on the first one. Does it mean the server is limiting the upload speed, or is something bound to the client?

**Comment by EricKotato** [comment]
Haven't noticed that. What if you start upload new file after previous is uploaded? Will speed be same?

**Comment by EricKotato** [comment]
Also, why you're reporting it to this repo? It's site repo. Please report it there: https://github.com/kotatogram/kotatogram-desktop/issues/new?template=BUG_REPORT.md
